apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghcr-credentials
  namespace: styrene-docs
spec:
  type: kv-v2
  mount: secret
  path: bootstrap/ghcr/styrene-lab
  refreshAfter: 1h
  vaultAuthRef: styrene-docs-vault-auth
  destination:
    name: ghcr-secret
    create: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      excludeRaw: true
      templates:
        .dockerconfigjson:
          text: |
            {"auths":{"{{ .Secrets.server }}":{"username":"{{ .Secrets.username }}","password":"{{ .Secrets.password }}","auth":"{{ printf "%s:%s" .Secrets.username .Secrets.password | b64enc }}"}}}
